{
    'name': 'School Management',
    'version': '17.0.4.0.0',
    'category': 'school management',
    'summary': 'its a school management module',
    'description': """ manage school system """,
    'depends': ['base', 'web', 'mail', 'sale', 'base_automation', 'website',
                'website_sale'],
    'data': ['security/ir_module_category.xml',
             'security/ir_rule_user.xml',
             'security/ir.model.access.csv',
             'data/ir_sequence_admission.xml',
             'data/ir_cron_attendence.xml',
             'data/ir_actions_server_user.xml',
             # 'data/ir_action_emp_user.xml',
             'data/manage_department_data.xml',
             'data/manage_class_data.xml',
             'data/manage_subject_data.xml',
             'data/email_template_event.xml',
             'data/ir_cron_email.xml',
             'views/res_partner_view.xml',
             'views/res_users_view.xml',
             'views/manage_department_view.xml',
             'views/manage_class_view.xml',
             'views/manage_subject_view.xml',
             'views/manage_clubs_view.xml',
             'views/manage_events_view.xml',
             'views/manage_academic_year_view.xml',
             'views/manage_leaves_view.xml',
             'views/teachers_view.xml',
             'views/office_staff_view.xml',
             'views/student_manage_view.xml',
             'views/student_registered_view.xml',
             'views/manage_exam_view.xml',
             'wizard/leave_wizard.xml',
             'wizard/event_wizard.xml',
             'wizard/club_wizard.xml',
             'wizard/student_wizard.xml',
             'wizard/exam_wizard.xml',
             'report/ir.actions_report.xml',
             'report/leave_report.xml',
             'report/club_report.xml',
             'report/student_report.xml',
             'report/exam_report.xml',
             'report/events_report.xml',
             'views/web_register_template.xml',
             'views/web_event_template.xml',
             'views/web_leave_template.xml',
             'views/event_snippet.xml',
             'views/events_template.xml',
             'views/school_management_menus.xml',
             ],
    'application': True,
    'license': 'LGPL-3',
    'assets': {
            'web.assets_backend': [
                'school_management/static/src/js/action_manage.js'
            ],
        'web.assets_frontend': [
                'school_management/static/src/css/style.css',
                'school_management/static/src/js/myScript.js',
                'school_management/static/src/xml/events_templates.xml',
                'school_management/static/src/js/event_snippet.js',
            ]
    },
}
